- name: Set-up enviorment
  hosts: "{{ ansible_limit | default('localhost') }}"
  roles:
    - role: basic-tools
      tags:
        - server
        - workstation
    - role: zsh
      tags:
        - server
        - workstation
        - zsh
    - role: go
      tags:
        - workstation
        - go
    - role: lazygit
      tags:
        - workstation
        - lazygit
    - role: node
      tags:
        - workstation
        - node
    - role: rust
      tags:
        - workstation
        - rust
    - role: neovim
      tags:
        - workstation
        - neovim
    - role: tmux
      tags:
        - server
        - workstation
        - tmux
    - role: useful-dirs
      tags:
        - workstation
    - role: vim
      tags:
        - server
        - workstation
        - vim
    - role: wsl
      tags:
        - workstation
        - wsl
      when: is_wsl
