- name: Set-up enviorment
  hosts: localhost
  roles:
    - role: basic-tools
      tags:
        - basic
        - server
        - workstation
    - role: zsh
      tags:
        - basic
        - server
        - workstation
        - zsh
    - role: wsl
      tags:
        - basic
        - workstation
        - wsl
      when: is_wsl
