- name: Set-up workstation enviorment
  hosts: "{{ ansible_limit | default('localhost') }}"
  vars:
    homebrew_path: /home/linuxbrew/.linuxbrew
  environment:
    PATH: "{{ ansible_env.PATH }}:{{homebrew_path}}/bin"
  roles:
    - role: basic-tools
    - role: build-essentials
    - role: git
      tags: [git]
    - role: homebrew
      homebrew_use_become: true
      tags: [homebrew]
    - role: useful-dirs
    - role: go
      go_role_should_install: false
      tags: [golang]
    - role: bash
    - role: fish
    - role: zsh
      zsh_set_default_shell: false
    - role: vim
    - role: neovim
      neovim_role_should_install: false
      tags: [neovim]
    - role: tmux
    - role: wsl
      when: is_wsl
