- name: Enable atim/lazygit Copr repository
  become: true
  tags:
    - use_become
  community.general.copr:
    name: atim/lazygit
    state: enabled
- name: Install lazygit
  become: true
  tags:
    - use_become
  dnf:
    name: "lazygit"
    state: present
