- name: Install basic tooling using the distro's package manager
  become: true
  tags:
    - use_become
    - use_package_mgr
  package:
    name:
      - curl
      - git
      - tmux
      - vim
      - zsh
    state: present
