# XDG-Dirs
cache_dir: "{{ ansible_env.XDG_CACHE_HOME is defined | ternary(ansible_env.XDG_CACHE_HOME, ansible_env.HOME + '/.cache') }}"
config_dir: "{{ ansible_env.XDG_CONFIG_HOME is defined | ternary(ansible_env.XDG_CONFIG_HOME, ansible_env.HOME + '/.config') }}"
data_dir: "{{ ansible_env.XDG_DATA_HOME is defined | ternary(ansible_env.XDG_DATA_HOME, ansible_env.HOME + '/.local/share') }}"
state_dir: "{{ ansible_env.XDG_STATE_HOME is defined | ternary(ansible_env.XDG_STATE_HOME, ansible_env.HOME + '/.local/state') }}"

home: "{{ ansible_env.HOME }}"
user: "{{ ansible_env.USER }}"

is_wsl: "{{ 'WSL2' in ansible_kernel }}"
