- name: Create data directory
  file:
    path: "{{ data_dir }}"
    state: directory
    mode: 0755
- name: install oh-my-zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ ohmyzsh_dir }}"
    clone: true
    depth: 1
- name: install powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ohmyzsh_dir }}/custom/themes/powerlevel10k"
    clone: true
    depth: 1
- name: install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ ohmyzsh_dir }}/custom/plugins/zsh-autosuggestions"
    clone: true
    depth: 1
- name: "Create {{ config_dir }}/shell"
  file:
    path: "{{ config_dir }}/shell"
    state: directory
    mode: 0755
- name: Create local-shell.sh
  file:
    path: "{{ config_dir }}/shell/local-shell.sh"
    state: touch
    modification_time: preserve
    mode: 0644
- name: Copy p10k file
  copy:
    src: "p10k.zsh"
    dest: "{{ config_dir }}/shell/p10k.zsh"
    mode: 0644
- name: Create state directory
  file:
    path: "{{ state_dir }}/zsh"
    state: directory
    mode: 0755
- name: Create cache directory
  file:
    path: "{{ cache_dir }}/zsh"
    state: directory
    mode: 0755
- name: Move .zsh_history
  command: mv "{{ home }}/.zsh_history" "{{ state_dir }}/zsh/.zsh_history"
  args:
    creates: "{{ state_dir }}/zsh/.zsh_history"
    removes: "{{ home }}/.zsh_history"
- name: Check bat is installed
  command: bash -c 'command -v bat'
  register: check_if_bat_is_installed
  changed_when: false
  ignore_errors: true
- name: Check if zoxide is installed
  command: bash -c 'command -v zoxide'
  register: check_if_zoxide_is_installed
  changed_when: false
  ignore_errors: true
- name: Check if homebrew is installed
  stat:
    path: "{{ homebrew_path }}"
  register: check_if_homebrew_is_installed
  changed_when: false
  ignore_errors: true
- name: Copy .zshrc
  template:
    src: zshrc.j2
    dest: "{{ home }}/.zshrc"
    mode: 0644
- name: Change default shell to zsh
  become: true
  user:
    name: "{{ user }}"
    shell: /bin/zsh
  when: set_default_shell
