syntax on
colorscheme onedark

set expandtab
set foldmethod=indent
set foldlevelstart=99
set shiftwidth=4
set smarttab
set softtabstop=0
set tabstop=4

" Allow saving of files as sudo when I forgot to start vim using sudo.
cmap w!! w !sudo tee > /dev/null %
