- name: Create {{ config_dir }}/tmux
  file:
    path: "{{ config_dir }}/tmux"
    state: directory
    mode: 0755
- name: Copy tmux.conf
  copy:
    src: tmux.conf
    dest: "{{ config_dir }}/tmux/tmux.conf"
    mode: 0644
- name: Create plugins directory
  file:
    path: "{{ data_dir }}/tmux/plugins"
    state: directory
    mode: 0755
- name: Create .local/bin
  file:
    path: "{{ home }}/.local/bin"
    state: directory
    mode: 0755
- name: Install tb script
  copy:
    src: "tb.sh"
    dest: "{{ home }}/.local/bin/tb"
    mode: 0755
