- name: Create .local/bin directory
  file:
    path: "{{ home }}/.local/bin"
    state: directory
    mode: 0755
- name: Download npiperelay binary
  get_url:
    url: "https://github.com/albertony/npiperelay/releases/latest/download/npiperelay_windows_amd64.exe"
    dest: "{{ home }}/.local/bin/npiperelay.exe"
    mode: 0755
- name: Create wsl profile
  template:
    src: wsl-profile.sh
    dest: "{{ config_dir }}/shell/wsl-profile.sh"
    mode: 0644
- name: Install Neovide WSL wrapper
  copy:
    src: neovide.sh
    dest: "{{ home }}/.local/bin/neovide"
    mode: 0755
- name: Install socat package
  become: true
  tags:
    - use_become
  package:
    name: socat
    state: present
- name: Systemd SSH agent
  when: uses_systemd
  block:
    - name: "Create user's systmed folder"
      file:
        path: "{{ config_dir }}/systemd/user"
        state: directory
        mode: 0755
    - name: "Copy systemd WSL SSH service"
      copy:
        src: wsl-ssh-agent.service
        dest: "{{ config_dir }}/systemd/user/wsl-ssh-agent.service"
      register: copy_service_file
    - name: Reload Systemd user daemon
      when: copy_service_file.changed
      systemd:
        scope: user
        daemon_reload: true
    - name: "Enable WSL SSH service"
      systemd:
        scope: user
        name: wsl-ssh-agent.service
        state: started
        enabled: true
