- name: Install neovim and dependencies
  become: true
  tags:
    - use_become
  dnf:
    name:
      - neovim
      - fzf
      - make
      - automake
      - gcc
      - gcc-c++
    state: present
