- name: Install neovim and dependencies
  become: true
  tags:
    - use_become
    - use_package_mgr
  zypper:
    name: ["neovim", "fzf"]
    state: present
- name: Install C/C++ build tools
  become: true
  tags:
    - use_become
    - use_package_mgr
  zypper:
    name: ["devel_C_C++"]
    type: pattern
    state: present
