- include_tasks: install-{{ ansible_pkg_mgr }}.yaml
- name: Clone neovim config
  git:
    repo: https://github.com/claudio4/nvim-config.git
    dest: "{{ config_dir }}/nvim"
    clone: true
    depth: 1
  # This is a hack to avoid the task failing when there are local modifications
  register: repo_clone
  failed_when:
    - repo_clone.failed
    - not 'Local modifications exist' in repo_clone.msg

